// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_Fix_SeBuffers","status":true,"description":"SEバッファ修正 1.0.0\r\n不具合修正プラグインです。複数の演奏中のSEを正常に停止できるようにします。","parameters":{}}
];
